<?php

namespace App\Support;

final class ToolRegistry
{
    public static function all(): array
    {
        return [
            [
                'slug' => 'json-formatter',
                'name' => 'JSON Formatter',
                'category' => 'JSON',
                'description' => 'Format and validate JSON instantly.',
                'icon' => '{}',
                'tags' => ['json', 'format', 'pretty', 'validate'],
                'popular' => true,
                'status' => 'ready',
            ],
            [
                'slug' => 'json-validator',
                'name' => 'JSON Validator',
                'category' => 'JSON',
                'description' => 'Check JSON syntax with readable errors.',
                'icon' => '{}',
                'tags' => ['json', 'validate', 'syntax'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'json-minifier',
                'name' => 'JSON Minifier',
                'category' => 'JSON',
                'description' => 'Compress JSON into a clean, compact payload.',
                'icon' => '{}',
                'tags' => ['json', 'minify', 'compress'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'json-escape',
                'name' => 'JSON Escape',
                'category' => 'JSON',
                'description' => 'Escape JSON for strings, logs, and payloads.',
                'icon' => '{}',
                'tags' => ['json', 'escape', 'string'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'json-unescape',
                'name' => 'JSON Unescape',
                'category' => 'JSON',
                'description' => 'Turn escaped JSON back into readable text.',
                'icon' => '{}',
                'tags' => ['json', 'unescape', 'string'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'json-diff',
                'name' => 'JSON Diff',
                'category' => 'JSON',
                'description' => 'Compare two JSON documents without ordering noise.',
                'icon' => '{}',
                'tags' => ['json', 'diff', 'compare'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'base64',
                'name' => 'Base64 Encode / Decode',
                'category' => 'Encoding',
                'description' => 'Encode or decode UTF-8 text safely.',
                'icon' => '64',
                'tags' => ['base64', 'encode', 'decode'],
                'popular' => true,
                'status' => 'ready',
            ],
            [
                'slug' => 'url-encode',
                'name' => 'URL Encode / Decode',
                'category' => 'Encoding',
                'description' => 'Prepare query strings and URL components.',
                'icon' => '%',
                'tags' => ['url', 'uri', 'encode', 'decode'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'html-encode',
                'name' => 'HTML Encode / Decode',
                'category' => 'Encoding',
                'description' => 'Escape and restore HTML entities safely.',
                'icon' => '<>',
                'tags' => ['html', 'entity', 'escape', 'decode'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'uuid-generator',
                'name' => 'UUID Generator',
                'category' => 'Generator',
                'description' => 'Generate clean UUID v4 values in batches.',
                'icon' => 'id',
                'tags' => ['uuid', 'random', 'identifier'],
                'popular' => true,
                'status' => 'ready',
            ],
            [
                'slug' => 'random-string-generator',
                'name' => 'Random String Generator',
                'category' => 'Generator',
                'description' => 'Generate strings with custom case, number, and symbol rules.',
                'icon' => 'abc',
                'tags' => ['random', 'string', 'generator', 'characters'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'password-generator',
                'name' => 'Password Generator',
                'category' => 'Generator',
                'description' => 'Create strong passwords without storing them.',
                'icon' => 'key',
                'tags' => ['password', 'random', 'security'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'timestamp',
                'name' => 'Timestamp Converter',
                'category' => 'Date & Time',
                'description' => 'Move between Unix timestamps and readable dates.',
                'icon' => 'time',
                'tags' => ['timestamp', 'date', 'unix'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'text-case',
                'name' => 'Text Case Converter',
                'category' => 'Text',
                'description' => 'Switch text between uppercase, lowercase, and title case.',
                'icon' => 'abc',
                'tags' => ['text', 'case', 'format'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'text-cleaner',
                'name' => 'Whitespace Cleaner',
                'category' => 'Text',
                'description' => 'Normalize spaces and remove noisy text formatting.',
                'icon' => 'clean',
                'tags' => ['text', 'clean', 'whitespace'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'slug-generator',
                'name' => 'Slug Generator',
                'category' => 'Text',
                'description' => 'Create clean, URL-safe slugs from plain text.',
                'icon' => '#',
                'tags' => ['text', 'slug', 'url'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'hash-generator',
                'name' => 'Hash Generator',
                'category' => 'Security',
                'description' => 'Create hashes for strings and verify identity checks.',
                'icon' => '#',
                'tags' => ['hash', 'security', 'crypto'],
                'popular' => true,
                'status' => 'ready',
            ],
            [
                'slug' => 'hash-compare',
                'name' => 'Hash Compare',
                'category' => 'Security',
                'description' => 'Compare a value against a stored hash quickly.',
                'icon' => '==',
                'tags' => ['hash', 'compare', 'security'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'number-format',
                'name' => 'Number Formatter',
                'category' => 'Number',
                'description' => 'Format and localize numeric values for human readability.',
                'icon' => '123',
                'tags' => ['number', 'format', 'decimal'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'number-base',
                'name' => 'Base Converter',
                'category' => 'Number',
                'description' => 'Convert numbers between decimal, binary, octal, and hex.',
                'icon' => '10→2',
                'tags' => ['number', 'base', 'convert'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'color-hex-rgb',
                'name' => 'HEX to RGB',
                'category' => 'Color',
                'description' => 'Translate HEX color strings into usable RGB values.',
                'icon' => '#',
                'tags' => ['color', 'hex', 'rgb'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'color-rgb-hex',
                'name' => 'RGB to HEX',
                'category' => 'Color',
                'description' => 'Convert RGB channels into clean HEX output.',
                'icon' => 'rgb',
                'tags' => ['color', 'rgb', 'hex'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'ip-validator',
                'name' => 'IP Validator',
                'category' => 'Network',
                'description' => 'Check whether an address is a valid IPv4 or IPv6 string.',
                'icon' => 'IP',
                'tags' => ['ip', 'network', 'validation'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'ip-classifier',
                'name' => 'IP Classifier',
                'category' => 'Network',
                'description' => 'Identify whether an address is public, private, or invalid.',
                'icon' => 'net',
                'tags' => ['ip', 'network', 'classify'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'curl-generator',
                'name' => 'cURL Generator',
                'category' => 'API',
                'description' => 'Generate cURL commands from HTTP configuration.',
                'icon' => '>$',
                'tags' => ['curl', 'http', 'api', 'headers'],
                'popular' => true,
                'status' => 'ready',
            ],
            [
                'slug' => 'http-request',
                'name' => 'HTTP Request Builder',
                'category' => 'API',
                'description' => 'Shape API requests with a focused workspace.',
                'icon' => '->',
                'tags' => ['http', 'request', 'api', 'rest'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'regex-tester',
                'name' => 'Regex Tester',
                'category' => 'Developer',
                'description' => 'Inspect matches, groups, and positions.',
                'icon' => '.*',
                'tags' => ['regex', 'pattern', 'developer'],
                'popular' => false,
                'status' => 'ready',
            ],
            [
                'slug' => 'jwt-decoder',
                'name' => 'JWT Decoder',
                'category' => 'Developer',
                'description' => 'Decode JWT header and payload locally.',
                'icon' => 'jwt',
                'tags' => ['jwt', 'token', 'json', 'auth'],
                'popular' => true,
                'status' => 'ready',
            ],
            [
                'slug' => 'dummy-json',
                'name' => 'Dummy JSON Generator',
                'category' => 'Developer',
                'description' => 'Generate realistic fixture data for development.',
                'icon' => '[]',
                'tags' => ['json', 'dummy', 'fixtures', 'mock'],
                'popular' => false,
                'status' => 'ready',
            ],
        ];
    }

    public static function categories(): array
    {
        return ['JSON', 'Encoding', 'Generator', 'Date & Time', 'Text', 'Security', 'Number', 'Color', 'Network', 'API', 'Developer'];
    }

    public static function find(string $slug): ?array
    {
        return collect(self::all())->firstWhere('slug', $slug);
    }
}